#!/usr/bin/env bash

command_name="$1"

case $command_name in
  lint)
    ./gradlew clean lint
    ./gradlew detekt --auto-correct
    ;;
  lint-check)
    ./gradlew clean lint
    ./gradlew detekt
    ;;
esac