[versions]
# Demo App
appcompatVersion = "1.7.0"
browserSwitchVersion = "2.3.1"
gradleVersion = "8.3.2"
junitVersion = "4.13.2"
kotlinVersion = "1.9.10"
lifecycleRuntimeVersion = "2.7.0"
mockitoCoreVersion = "5.7.0"
robolectricVersion = "4.11.1"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
browser-switch = { module = "com.braintreepayments.api:browser-switch", version.ref = "browserSwitchVersion" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradleVersion" }
junit = { module = "junit:junit", version.ref = "junitVersion" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "lifecycleRuntimeVersion" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCoreVersion" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectricVersion" }

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }
