name: Instrumentation tests
on: [pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      EMULATOR_OPTIONS: -no-window -gpu swiftshader_indirect -dns-server 8.8.8.8 -noaudio -no-boot-anim -camera-back none -memory 4096 -feature GLDirectMem,HasSharedSlotsHostMemoryAllocator
    strategy:
      fail-fast: false
      matrix:
        include:
          - api-level: 31
            target: google_apis
          - api-level: 35
            target: google_apis
          - api-level: "37.0"
            target: google_apis_ps16k
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: run tests
        id: run_tests
        uses: reactivecircus/android-emulator-runner@v2
        continue-on-error: true
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: pixel_7_pro
          emulator-options: ${{ env.EMULATOR_OPTIONS }}
          emulator-boot-timeout: 900
          disk-size: 8G
          script: |
            adb wait-for-device
            printf '_ --disable-fre --no-default-browser-check --no-first-run\n' > chrome-command-line
            adb push chrome-command-line /data/local/tmp/chrome-command-line
            adb shell chmod 777 /data/local/tmp/chrome-command-line
            ./gradlew :Demo:connectedCheck --stacktrace

      - name: retry tests
        if: steps.run_tests.outcome == 'failure'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: pixel_7_pro
          emulator-options: ${{ env.EMULATOR_OPTIONS }}
          emulator-boot-timeout: 900
          disk-size: 8G
          script: |
            adb wait-for-device
            printf '_ --disable-fre --no-default-browser-check --no-first-run\n' > chrome-command-line
            adb push chrome-command-line /data/local/tmp/chrome-command-line
            adb shell chmod 777 /data/local/tmp/chrome-command-line
            ./gradlew :Demo:connectedCheck --stacktrace
