name: Tests
on: [pull_request]
jobs:
  unit_test_job:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17.0.8'
          distribution: 'zulu'
      - name: Unit Tests
        run: ./gradlew --stacktrace testRelease
