name: Tests
on: [pull_request]
jobs:
  unit_test_job:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Java
        uses: ./.github/actions/setup_java
      - name: Unit Tests
        run: ./gradlew --stacktrace testRelease
